import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export const APP_NAME = process.env.APP_NAME;
export const APP_NAME_CLIENT = process.env.NEXT_PUBLIC_APP_NAME;
export const APP_MODE = process.env.APP_MODE;
export const APP_MODE_CLIENT = process.env.NEXT_PUBLIC_APP_MODE;

export const DESCRIPTION = "Generated by create next app";
export const INFINITY_QUERY = 10;

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
